export const getDefaultHtmlTemplate = (assessmentType: string): Record<string, any> => ({
  id: `default_${assessmentType}`,
  name: `Default ${assessmentType} Template`,
  content: `
        <!DOCTYPE html>
        <html>
        <head>
          <title>{{CLIENT_NAME}} - ${assessmentType.toUpperCase()} Assessment Report</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .header { border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
            .section { margin-bottom: 20px; }
            .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Financial Suitability Assessment Report</h1>
            <p><strong>Client:</strong> {{CLIENT_NAME}}</p>
            <p><strong>Date:</strong> {{ASSESSMENT_DATE}}</p>
            <p><strong>Version:</strong> {{VERSION_NUMBER}}</p>
          </div>
          <div class="content">
            {{CONTENT}}
          </div>
          <div class="footer">
            <p>This document is confidential and proprietary.</p>
            <p>Generated by Financial Advisory Platform</p>
          </div>
        </body>
        </html>
      `
});

export const mapAssessmentToVariables = (
  type: string,
  assessment: Record<string, any>,
  client: any
): Record<string, any> => {
  const baseVariables = {
    CLIENT_NAME: (assessment.personal_circumstances?.client_name as string) ||
      `${client.personal_details?.firstName || ''} ${client.personal_details?.lastName || ''}`.trim() ||
      'Client',
    CLIENT_EMAIL: client.contact_details?.email || '',
    ASSESSMENT_DATE: new Date().toLocaleDateString('en-GB'),
    ADVISOR_NAME: 'Professional Advisor',
    VERSION_NUMBER: assessment.version_number || 1,
    IS_FINAL: assessment.is_final || false,
    IS_DRAFT: assessment.is_draft || true,
    FIRM_NAME: 'Financial Advisory Services',
    FIRM_ADDRESS: '123 Financial Street, London, UK',
    FIRM_FCA_NUMBER: 'FCA123456'
  };

  const typeSpecificVariables = getTypeSpecificVariables(type, assessment, client);

  return {
    ...baseVariables,
    ...typeSpecificVariables,
    CONTENT: generateFormattedContent(type, assessment, client)
  };
};

const generateFormattedContent = (
  type: string,
  assessment: Record<string, any>,
  client: any
): string => {
  let content = '<div class="assessment-content">';

  if (type === 'suitability') {
    const personal = assessment.personal_circumstances || {};
    const objectives = assessment.investment_objectives || {};
    const risk = assessment.risk_assessment || {};
    const recommendation = assessment.recommendations || {};
    const financial = assessment.financial_situation || {};

    content += `
        <div class="section">
          <h2>Client Snapshot</h2>
          <p>Name: ${personal.client_name || 'Not provided'}</p>
          <p>Age: ${personal.age || ''}</p>
          <p>Employment Status: ${personal.employment_status || ''}</p>
        </div>
        <div class="section">
          <h2>Investment Objectives</h2>
          <p>Primary Objective: ${objectives.primary_objective || 'Not specified'}</p>
          <p>Investment Amount: £${objectives.investment_amount || 0}</p>
          <p>Time Horizon: ${objectives.time_horizon || 'Not specified'}</p>
          <p>Income Requirement: ${objectives.income_requirements || 'Not specified'}</p>
        </div>
        <div class="section">
          <h2>Risk Assessment</h2>
          <p>Risk Profile: ${risk.attitude_to_risk || 'Moderate'}</p>
          <p>Capacity for Loss: ${risk.capacity_for_loss || 'Medium'}</p>
          <p>Max Acceptable Loss: ${risk.max_acceptable_loss || ''}%</p>
        </div>
        <div class="section">
          <h2>Financial Snapshot</h2>
          <p>Annual Income: £${financial.annual_income || 0}</p>
          <p>Monthly Expenditure: £${financial.monthly_expenditure || 0}</p>
          <p>Liquid Assets: £${financial.liquid_assets || 0}</p>
        </div>
        <div class="section">
          <h2>Recommendations</h2>
          <p>Recommended Portfolio: ${recommendation.recommended_portfolio || 'Balanced'}</p>
          <p>Rationale: ${recommendation.recommendation_rationale || 'Based on your objectives and risk profile.'}</p>
          <p>Next Review: ${recommendation.next_review_date || 'Not set'}</p>
        </div>
      `;
  }

  content += '</div>';
  return content;
};

const getTypeSpecificVariables = (
  type: string,
  assessment: Record<string, any>,
  client: any
): Record<string, any> => {
  switch (type) {
    case 'atr':
      return {
        ATR_SCORE: assessment.total_score || 0,
        RISK_CATEGORY: assessment.risk_category || 'Not assessed',
        RISK_LEVEL: assessment.risk_level || 'Medium'
      };

    case 'cfl':
      return {
        CFL_SCORE: assessment.total_score || 0,
        CAPACITY_CATEGORY: assessment.capacity_category || 'Not assessed',
        MAX_LOSS_PERCENTAGE: assessment.max_loss_percentage || 0
      };

    case 'vulnerability':
      return {
        VULNERABILITY_STATUS: assessment.is_vulnerable ? 'Vulnerable' : 'Not Vulnerable',
        VULNERABILITY_FACTORS: assessment.vulnerability_factors || []
      };

    case 'suitability':
      return {
        RISK_PROFILE: assessment.risk_assessment?.attitude_to_risk || 'Moderate',
        RISK_CAPACITY: assessment.risk_assessment?.capacity_for_loss || 'Medium',
        INVESTMENT_AMOUNT: assessment.investment_objectives?.investment_amount || 0,
        TIME_HORIZON: assessment.investment_objectives?.time_horizon || 'Not specified',
        PRIMARY_OBJECTIVE: assessment.investment_objectives?.primary_objective || 'Not specified',
        RECOMMENDED_PORTFOLIO: assessment.recommendations?.recommended_portfolio || 'Not specified',
        RECOMMENDATION_RATIONALE: assessment.recommendations?.recommendation_rationale || 'See detailed rationale in report.',
        NEXT_REVIEW_DATE: assessment.recommendations?.next_review_date || '',
        COMPLETION_PERCENTAGE: assessment.completion_percentage || 0,
        CONTACT_EMAIL: assessment.contact_details?.email || '',
        CONTACT_PHONE: assessment.contact_details?.phone || ''
      };

    default:
      return {};
  }
};
