// =====================================================
// FILE: src/components/suitability/SuitabilityField.tsx
// COMPLETE FIELD COMPONENT - ALL INPUT ISSUES FIXED
// =====================================================

import React, { useRef } from 'react'
import { SuitabilityField as FieldType } from '@/types/suitability'
import { SmartAddressField } from '@/components/suitability/SmartAddressField'
import { cn } from '@/lib/utils'

interface SuitabilityFieldProps {
  field: FieldType
  value: any
  onChange: (value: any) => void
  error?: string
  className?: string
}

export const SuitabilityField: React.FC<SuitabilityFieldProps> = ({
  field,
  value,
  onChange,
  error,
  className
}) => {
  const isCalculated = Boolean(field.calculate)
  const isAutoGenerated = Boolean(field.autoGenerate)
  
  // Format phone number to preserve leading zeros
  const formatPhoneNumber = (input: string) => {
    // Remove any non-digit except + at the start
    let cleaned = input.replace(/(?!^\+)\D/g, '')
    
    // Preserve UK format with leading 0
    if (cleaned.startsWith('0') || input.startsWith('0')) {
      // Don't remove leading 0 for UK numbers
      return input
    }
    
    return cleaned
  }
  
  return (
    <div className={cn("space-y-2", className)}>
      <label className="block text-sm font-medium text-gray-700">
        {field.label}
        {field.required && <span className="text-red-500 ml-1">*</span>}
        {isAutoGenerated && <span className="text-blue-500 ml-1">(auto)</span>}
        {isCalculated && <span className="text-green-500 ml-1">(calculated)</span>}
      </label>
      
      {field.type === 'address' ? (
        <SmartAddressField
          value={value || ''}
          onChange={onChange}
          placeholder={field.placeholder}
          required={field.required}
          error={error}
        />
      ) : field.type === 'text' ? (
        <input
          type="text"
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          placeholder={field.placeholder}
          readOnly={isAutoGenerated || isCalculated}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300",
            (isAutoGenerated || isCalculated) && "bg-gray-50"
          )}
        />
      ) : field.type === 'number' ? (
        <input
          type="text" // Use text to have better control
          inputMode="numeric" // Mobile numeric keyboard
          pattern="[0-9]*" // Numeric pattern
          value={value || ''}
          onChange={(e) => {
            // Only allow numbers and decimal point
            const newValue = e.target.value.replace(/[^\d.]/g, '')
            onChange(newValue)
          }}
          onFocus={(e) => {
            // Select all text on focus
            e.target.select()
          }}
          onKeyDown={(e) => {
            // Clear field if it's just "0" and user types a number
            const target = e.target as HTMLInputElement
            if (target.value === '0' && e.key >= '1' && e.key <= '9') {
              target.value = ''
            }
          }}
          placeholder={field.placeholder}
          readOnly={isCalculated}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300",
            isCalculated && "bg-gray-50"
          )}
        />
      ) : field.type === 'select' ? (
        <select
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        >
          <option value="">Select {field.label}...</option>
          {field.options?.map(option => (
            <option key={option} value={option}>{option}</option>
          ))}
        </select>
      ) : field.type === 'textarea' ? (
        <textarea
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          placeholder={field.placeholder}
          rows={4}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        />
      ) : field.type === 'radio' ? (
        <div className="space-y-2">
          {field.options?.map(option => (
            <label key={option} className="flex items-center space-x-2">
              <input
                type="radio"
                value={option}
                checked={value === option}
                onChange={(e) => onChange(e.target.value)}
              />
              <span className="text-sm">{option}</span>
            </label>
          ))}
        </div>
      ) : field.type === 'checkbox' ? (
        <div className="space-y-2">
          {field.options?.map(option => (
            <label key={option} className="flex items-center space-x-2">
              <input
                type="checkbox"
                checked={Array.isArray(value) ? value.includes(option) : false}
                onChange={(e) => {
                  const current = Array.isArray(value) ? value : []
                  if (e.target.checked) {
                    onChange([...current, option])
                  } else {
                    onChange(current.filter((v: string) => v !== option))
                  }
                }}
              />
              <span className="text-sm">{option}</span>
            </label>
          ))}
        </div>
      ) : field.type === 'date' ? (
        <input
          type="date"
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        />
      ) : field.type === 'email' ? (
        <input
          type="email"
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          placeholder={field.placeholder || 'email@example.com'}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        />
      ) : field.type === 'tel' ? (
        <input
          type="tel"
          value={value || ''}
          onChange={(e) => {
            // Preserve the input exactly as typed (including leading 0)
            const formattedValue = formatPhoneNumber(e.target.value)
            onChange(formattedValue)
          }}
          onFocus={(e) => {
            // Don't select phone numbers on focus
            e.target.setSelectionRange(e.target.value.length, e.target.value.length)
          }}
          placeholder={field.placeholder || '07123 456789'}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        />
      ) : null}
      
      {field.helpText && (
        <p className="text-xs text-gray-500">{field.helpText}</p>
      )}
      
      {error && (
        <p className="text-sm text-red-600">{error}</p>
      )}
    </div>
  )
}

export default SuitabilityField