// =====================================================
// FILE: src/components/suitability/SuitabilityField.tsx
// COMPLETE FIELD COMPONENT - ALL INPUT ISSUES FIXED
// =====================================================

import React, { useRef, memo, useCallback } from 'react'
import { Database } from 'lucide-react'
import { SuitabilityField as FieldType } from '@/types/suitability'
import { SmartAddressField } from '@/components/suitability/SmartAddressField'
import { cn } from '@/lib/utils'

interface SuitabilityFieldProps {
  field: FieldType
  value: any
  onChange: (value: any) => void
  error?: string
  className?: string
  isPulledFromProfile?: boolean // Indicates field was auto-populated from client profile
}

export const SuitabilityField = memo(function SuitabilityField({
  field,
  value,
  onChange,
  error,
  className,
  isPulledFromProfile = false
}: SuitabilityFieldProps) {
  const isCalculated = Boolean(field.calculate)
  const isAutoGenerated = Boolean(field.autoGenerate)
  const showPulledIndicator = isPulledFromProfile && value
  const datalistId =
    field.type === 'text' && field.options?.length ? `suitability-datalist-${field.id}` : undefined
  
  // Format phone number to preserve leading zeros
  const formatPhoneNumber = (input: string) => {
    // Remove any non-digit except + at the start
    let cleaned = input.replace(/(?!^\+)\D/g, '')
    
    // Preserve UK format with leading 0
    if (cleaned.startsWith('0') || input.startsWith('0')) {
      // Don't remove leading 0 for UK numbers
      return input
    }
    
    return cleaned
  }

  // Backward-compatible checkbox value normalization (older drafts may store newline strings)
  const normalizeCheckboxValue = (raw: any): string[] => {
    if (Array.isArray(raw)) return raw.filter((v): v is string => typeof v === 'string')
    if (typeof raw === 'string') {
      return raw
        .split(/[\n,]+/)
        .map((v) => v.trim())
        .filter(Boolean)
    }
    return []
  }
  
  return (
    <div className={cn("space-y-2", className)}>
      <div className="flex items-center justify-between">
        <label className="block text-sm font-medium text-gray-700">
          {field.label}
          {field.required && <span className="text-red-500 ml-1">*</span>}
          {isAutoGenerated && <span className="text-blue-500 ml-1">(auto)</span>}
          {isCalculated && <span className="text-green-500 ml-1">(calculated)</span>}
        </label>
        {showPulledIndicator && (
          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-blue-50 text-blue-700 border border-blue-200">
            <Database className="h-3 w-3" />
            From profile
          </span>
        )}
      </div>
      
      {field.type === 'address' ? (
        <SmartAddressField
          value={value || ''}
          onChange={onChange}
          placeholder={field.placeholder}
          required={field.required}
          error={error}
        />
      ) : field.type === 'text' ? (
        <>
          <input
            type="text"
            value={value || ''}
            onChange={(e) => onChange(e.target.value)}
            placeholder={field.placeholder}
            readOnly={isAutoGenerated || isCalculated}
            list={datalistId}
            className={cn(
              "w-full p-2 border rounded-md",
              error ? "border-red-500" : "border-gray-300",
              (isAutoGenerated || isCalculated) && "bg-gray-50"
            )}
          />
          {datalistId && (
            <datalist id={datalistId}>
              {field.options?.map(option => (
                <option key={option} value={option} />
              ))}
            </datalist>
          )}
        </>
      ) : field.type === 'number' ? (
        <input
          type="text" // Use text to have better control
          inputMode="numeric" // Mobile numeric keyboard
          pattern="[0-9]*" // Numeric pattern
          value={value || ''}
          onChange={(e) => {
            // Only allow numbers and decimal point
            const newValue = e.target.value.replace(/[^\d.]/g, '')
            onChange(newValue)
          }}
          onFocus={(e) => {
            // Select all text on focus
            e.target.select()
          }}
          onKeyDown={(e) => {
            // Clear field if it's just "0" and user types a number
            const target = e.target as HTMLInputElement
            if (target.value === '0' && e.key >= '1' && e.key <= '9') {
              target.value = ''
            }
          }}
          placeholder={field.placeholder}
          readOnly={isCalculated}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300",
            isCalculated && "bg-gray-50"
          )}
        />
      ) : field.type === 'select' ? (
        <select
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        >
          <option value="">Select {field.label}...</option>
          {field.options?.map(option => (
            <option key={option} value={option}>{option}</option>
          ))}
        </select>
      ) : field.type === 'textarea' ? (
        <textarea
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          placeholder={field.placeholder}
          rows={4}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        />
      ) : field.type === 'list' ? (
        <div className="space-y-2">
          {Array.isArray(value) && value.length > 0 ? (
            value.map((item: string, index: number) => (
              <div key={`${field.id}-${index}`} className="flex items-center gap-2">
                <input
                  type="text"
                  value={item || ''}
                  onChange={(e) => {
                    const next = [...value]
                    next[index] = e.target.value
                    onChange(next.filter((entry) => entry && entry.trim().length > 0))
                  }}
                  placeholder={field.placeholder}
                  className={cn(
                    "w-full p-2 border rounded-md",
                    error ? "border-red-500" : "border-gray-300"
                  )}
                />
                <button
                  type="button"
                  className="text-xs text-gray-500"
                  onClick={() => {
                    const next = value.filter((_: string, idx: number) => idx !== index)
                    onChange(next)
                  }}
                >
                  Remove
                </button>
              </div>
            ))
          ) : (
            <input
              type="text"
              value=""
              onChange={(e) => onChange([e.target.value])}
              placeholder={field.placeholder}
              className={cn(
                "w-full p-2 border rounded-md",
                error ? "border-red-500" : "border-gray-300"
              )}
            />
          )}
          <button
            type="button"
            className="text-xs text-blue-600"
            onClick={() => onChange([...(Array.isArray(value) ? value : []), ''])}
          >
            Add another
          </button>
        </div>
      ) : field.type === 'radio' ? (
        <div className="space-y-2">
          {field.options?.map(option => (
            <label key={option} className="flex items-center space-x-2">
              <input
                type="radio"
                value={option}
                checked={value === option}
                onChange={(e) => onChange(e.target.value)}
              />
              <span className="text-sm">{option}</span>
            </label>
          ))}
        </div>
      ) : field.type === 'checkbox' ? (
        <div className="space-y-2">
          {field.options?.map(option => (
            <label key={option} className="flex items-center space-x-2">
              <input
                type="checkbox"
                checked={normalizeCheckboxValue(value).includes(option)}
                onChange={(e) => {
                  const current = normalizeCheckboxValue(value)
                  if (e.target.checked) {
                    onChange([...current, option])
                  } else {
                    onChange(current.filter((v: string) => v !== option))
                  }
                }}
              />
              <span className="text-sm">{option}</span>
            </label>
          ))}
        </div>
      ) : field.type === 'date' ? (
        <input
          type="date"
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        />
      ) : field.type === 'email' ? (
        <input
          type="email"
          value={value || ''}
          onChange={(e) => onChange(e.target.value)}
          placeholder={field.placeholder || 'email@example.com'}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        />
      ) : field.type === 'tel' ? (
        <input
          type="tel"
          value={value || ''}
          onChange={(e) => {
            // Preserve the input exactly as typed (including leading 0)
            const formattedValue = formatPhoneNumber(e.target.value)
            onChange(formattedValue)
          }}
          onFocus={(e) => {
            // Don't select phone numbers on focus
            e.target.setSelectionRange(e.target.value.length, e.target.value.length)
          }}
          placeholder={field.placeholder || '07123 456789'}
          className={cn(
            "w-full p-2 border rounded-md",
            error ? "border-red-500" : "border-gray-300"
          )}
        />
      ) : null}
      
      {field.helpText && (
        <p className="text-xs text-gray-500">{field.helpText}</p>
      )}
      
      {error && (
        <p className="text-sm text-red-600">{error}</p>
      )}
    </div>
  )
})

export default SuitabilityField
