export const OCCUPATION_SUGGESTIONS = [
  'Accountant',
  'Actor',
  'Administrative Assistant',
  'Architect',
  'Artisan',
  'Auditor',
  'Banker',
  'Barber',
  'Barrister',
  'Beautician',
  'Biomedical Scientist',
  'Business Analyst',
  'Business Owner',
  'Carer',
  'Carpenter',
  'Chef',
  'Civil Engineer',
  'Cleaner',
  'Consultant',
  'Customer Service Advisor',
  'Data Analyst',
  'Data Scientist',
  'Dentist',
  'Designer',
  'Doctor',
  'Driver',
  'Electrician',
  'Engineer',
  'Entrepreneur',
  'Estate Agent',
  'Financial Adviser',
  'Financial Analyst',
  'Firefighter',
  'Gardener',
  'Graphic Designer',
  'Hairdresser',
  'Healthcare Assistant',
  'HR Manager',
  'IT Support Technician',
  'Investment Manager',
  'Lawyer',
  'Lecturer',
  'Manager',
  'Marketing Manager',
  'Mechanic',
  'Nurse',
  'Office Manager',
  'Optician',
  'Paramedic',
  'Pharmacist',
  'Photographer',
  'Physiotherapist',
  'Plumber',
  'Police Officer',
  'Product Manager',
  'Project Manager',
  'Psychologist',
  'Recruiter',
  'Retail Assistant',
  'Sales Manager',
  'Scientist',
  'Security Guard',
  'Self-Employed',
  'Software Engineer',
  'Solicitor',
  'Student',
  'Teacher',
  'Tradesperson',
  'Unemployed',
  'Veterinarian',
  'Warehouse Operative'
]

