export const OCCUPATION_SUGGESTIONS = [
  'Account Executive',
  'Account Manager',
  'Accountant',
  'Actuary',
  'Actor',
  'Administrative Assistant',
  'Administrator',
  'Aerospace Engineer',
  'Agricultural Worker',
  'Air Traffic Controller',
  'Airline Pilot',
  'Analyst',
  'Architect',
  'Armed Forces',
  'Art Director',
  'Artisan',
  'Auditor',
  'Baker',
  'Bank Clerk',
  'Banker',
  'Barber',
  'Barista',
  'Barrister',
  'Beautician',
  'Biomedical Scientist',
  'Building Surveyor',
  'Builder',
  'Business Analyst',
  'Business Development Manager',
  'Business Owner',
  'Buyer',
  'Butcher',
  'Call Centre Advisor',
  'Care Manager',
  'Carer',
  'Carpenter',
  'Chef',
  'Chemical Engineer',
  'Civil Engineer',
  'Cleaner',
  'Clinical Psychologist',
  'Coach',
  'Compliance Officer',
  'Consultant',
  'Construction Manager',
  'Content Creator',
  'Content Designer',
  'Copywriter',
  'Counsellor',
  'Customer Service Advisor',
  'Cyber Security Analyst',
  'Data Analyst',
  'Data Scientist',
  'Delivery Driver',
  'Dental Nurse',
  'Dentist',
  'Designer',
  'Developer',
  'Doctor',
  'Driver',
  'Electrician',
  'Engineer',
  'Entrepreneur',
  'Estate Agent',
  'Event Manager',
  'Executive Assistant',
  'Factory Worker',
  'Farm Manager',
  'Farmer',
  'Financial Adviser',
  'Financial Analyst',
  'Financial Planner',
  'Firefighter',
  'Flight Attendant',
  'Forklift Driver',
  'Gardener',
  'Graphic Designer',
  'Hairdresser',
  'Healthcare Assistant',
  'HR Adviser',
  'HR Manager',
  'IT Manager',
  'IT Support Technician',
  'Insurance Broker',
  'Investment Manager',
  'Journalist',
  'Judge',
  'Kitchen Assistant',
  'Lawyer',
  'Lecturer',
  'Librarian',
  'Logistics Manager',
  'Manager',
  'Marketing Manager',
  'Mechanic',
  'Medical Secretary',
  'Midwife',
  'Nurse',
  'Office Manager',
  'Operations Manager',
  'Optician',
  'Paramedic',
  'Paralegal',
  'Personal Trainer',
  'Pharmacist',
  'Photographer',
  'Physiotherapist',
  'Plumber',
  'Police Officer',
  'Product Manager',
  'Project Manager',
  'Psychologist',
  'Quantity Surveyor',
  'Receptionist',
  'Recruiter',
  'Retail Assistant',
  'Risk Manager',
  'Sales Manager',
  'Scientist',
  'Security Guard',
  'Self-Employed',
  'Social Worker',
  'Software Engineer',
  'Solicitor',
  'Student',
  'Supply Chain Manager',
  'Surveyor',
  'Teacher',
  'Teaching Assistant',
  'Technician',
  'Tradesperson',
  'Train Driver',
  'Translator',
  'Truck Driver',
  'UI Designer',
  'UX Designer',
  'Unemployed',
  'Veterinary Surgeon',
  'Warehouse Operative',
  'Web Designer',
  'Web Developer',
  'Writer'
]
